### PR TITLE
Updated to newer, safer encryption Method

### PR DESCRIPTION
**Pull request by 1day2die**
Also removed Trackers and accidently changed the Branding to mine, but you can easily fix that yourself.

The most important thing on this PR is the use of more modern encryption to make this whole thing more secure

### CODE REVIEW

**Comment by joachimmueller** [comment]
Thanks for the contribution. Maybe using the password as key for the database might be a security flaw if someone gets hold of the database, although the IV ist still needed. What do you think?

**Comment by joachimmueller** [comment]
Not quite, before the key was just a random ID for the entry with no connection to the password. I would feel better if we do not use the password as an entry ID.

**Comment by 1day2die** [comment]
ooh yeah, i get what you mean now. Ill update that. Goot point!

**Comment by 1day2die** [comment]
Its quite redundant when looking at the code but i see the use of it. Updated. Is this what you meant?

**Comment by joachimmueller** [comment]
I think you don's need to put the password in the database at all. The password and the IV will be passed in only by the URL parameter.

**Comment by 1day2die** [comment]
so the url would be `?key={key}+{password}+{IV}`  correct?

**Comment by joachimmueller** [comment]
I refactored the code a bit to fix the security issues:

* Update libraries
* Update encryption method
* Validate request parameters
* Keep compatibility with older, existing entries

Please check out https://github.com/wemove/read2burn/releases/tag/0.7.0

You may have to remerge your changes. Thanks for your contribution and time!

I am closing this PR.

**Comment by 1day2die** [comment]
Great work. Thanks for the Update! Will do

**Pull request closed without merging**
